### ISSUE TITLE
Request content length can sometimes be `None`

### ISSUE THREAD

**Issue by kennethklee** [Mashape/analytics-agent-python#3]
Handle `None` type for content length. This could happen when there is no content length header.

Have checks in WSGI and Django frameworks.

**Comment by dctdevelop** [comment]
+1

**Comment by dctdevelop** [comment]
#4

**Comment by dctdevelop** [comment]
#4

**Comment by kennethklee** [comment]
Ah sorry, I just realized you created a PR. I made a fix on both django and wsgi middleware in here:

Mashape/analytics-agent-python@675438e

**Comment by dctdevelop** [comment]
`pip install -U mashape-analytics` Thanks!

**Comment by sonicaghi** [comment]
@dctdevelop check Gelato for your developer hub.
